# Dependencies
markdown:         kramdown
highlighter:      pygments
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'React Hot Loader'
tagline:          'Pure JS live-editing for React'
description:      'Live edit your React components without unmounting or losing their state.'
url:              http://localhost:4000
paginate:         1
baseurl:          /react-hot-loader/
author:
  name:           Dan Abramov
  url:            https://twitter.com/dan_abramov
  email:          dan.abramov@me.com

# Custom vars
version:          0.2.0
github:
  repo:           http://github.com/gaearon/react-hot-loader
